services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: ${SERVER_VERSION:-1.23.3} # 🔥 Définit une valeur par défaut    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./sources:$PHP_USER_HOME_DIRECTORY
    ports:
      - $SERVER_PORT:80

  php:
    container_name: php
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./sources:$PHP_USER_HOME_DIRECTORY
      - ./db:/home/php/db
    entrypoint: ["/entrypoint.sh"]
    command: ["php-fpm"]


  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    user: root
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - default
